export type LEDirectoryEntry = {
    platform: string;
    category: string;
    portalUrl: string;
    portalLink?: string;
    contact: string;
};

export const leDirectoryData: LEDirectoryEntry[] = [
    { platform: "Facebook", category: "Social Media", portalUrl: "Portal Link", portalLink: "https://www.facebook.com/records/", contact: "—" },
    { platform: "WhatsApp", category: "Social Media", portalUrl: "Portal Link", portalLink: "https://www.whatsapp.com/records/", contact: "abuse@whatsapp.com" },
    { platform: "Instagram", category: "Social Media", portalUrl: "Meta LEOR", portalLink: "https://www.facebook.com/records", contact: "—" },
    { platform: "Twitter (X)", category: "Social Media", portalUrl: "Legal Requests", portalLink: "https://legalrequests.twitter.com/", contact: "—" },
    { platform: "YouTube", category: "Social Media", portalUrl: "Google LERS", portalLink: "https://lers.google.com/", contact: "support-in@google.com" },
    { platform: "Messenger", category: "Social Media", portalUrl: "Meta LEOR", portalLink: "https://www.facebook.com/records", contact: "—" },
    { platform: "ShareChat", category: "Social Media", portalUrl: "Help Center", portalLink: "https://help.sharechat.com/", contact: "nodalofficer@sharechat.co" },
    { platform: "Pinterest", category: "Social Media", portalUrl: "LE Page", portalLink: "https://help.pinterest.com/en/law-enforcement", contact: "—" },
    { platform: "Snapchat", category: "Social Media", portalUrl: "LE Page", portalLink: "https://snap.com/en-US/safety/safety-enforcement", contact: "grievance-officer-in@snap.com" },
    { platform: "LinkedIn", category: "Social Media", portalUrl: "LE Guidelines", portalLink: "https://www.linkedin.com/help/linkedin/answer/16880", contact: "—" },
    { platform: "Reddit", category: "Social Media", portalUrl: "LE Guidelines", portalLink: "https://www.redditinc.com/policies/guidelines-for-law-enforcement", contact: "grievance-officer-in@reddit.com" },
    { platform: "Imo", category: "Social Media", portalUrl: "Privacy Page", portalLink: "https://imo.im/policies/privacy_policy.html", contact: "—" },
    { platform: "MOJ", category: "Social Media", portalUrl: "MOJ Help", portalLink: "https://help.mojapp.in/", contact: "—" },
    { platform: "TikTok", category: "Social Media", portalUrl: "LE Page", portalLink: "https://www.tiktok.com/legal/page/global/law-enforcement/en", contact: "—" },
    { platform: "Vimeo", category: "Social Media", portalUrl: "Privacy", portalLink: "https://vimeo.com/privacy", contact: "—" },
    { platform: "Skype", category: "Social Media", portalUrl: "Microsoft LE", portalLink: "https://www.microsoft.com/en-us/corporate-responsibility/law-enforcement-requests-report", contact: "—" },
    { platform: "Signal", category: "Social Media", portalUrl: "Legal", portalLink: "https://signal.org/legal/", contact: "—" },
    { platform: "BOTIM", category: "Social Media", portalUrl: "Privacy", portalLink: "https://botim.me/privacy/", contact: "—" },
    { platform: "Discord", category: "Social Media", portalUrl: "Legal", portalLink: "https://dis.gd/legal", contact: "abuse@discord.com" },
    { platform: "Microsoft Teams", category: "Social Media", portalUrl: "Microsoft LE", portalLink: "https://www.microsoft.com/en-us/corporate-responsibility/law-enforcement-requests-report", contact: "—" },
    { platform: "Zoom", category: "Social Media", portalUrl: "Trust Form", portalLink: "https://zoom.us/trust-form", contact: "—" },
    { platform: "WeChat", category: "Social Media", portalUrl: "Privacy", portalLink: "https://www.wechat.com/en/privacy_policy.html", contact: "—" },
    { platform: "Gmail", category: "Email", portalUrl: "Google LERS", portalLink: "https://lers.google.com/", contact: "support-in@google.com" },
    { platform: "Yahoo", category: "Email", portalUrl: "Yahoo LE", portalLink: "https://lawenforcementrequests.oath.com/", contact: "—" },
    { platform: "RediffMail", category: "Email", portalUrl: "Grievance", portalLink: "https://www.rediff.com/grievances.html", contact: "—" },
    { platform: "Outlook", category: "Email", portalUrl: "Microsoft LE", portalLink: "https://www.microsoft.com/en-us/corporate-responsibility/law-enforcement-requests-report", contact: "—" },
    { platform: "ProtonMail", category: "Email", portalUrl: "LE Page", portalLink: "https://proton.me/legal/law-enforcement", contact: "—" },
    { platform: "iCloud", category: "Email", portalUrl: "Apple LE", portalLink: "https://lep.apple.com/", contact: "lawenforcement@apple.com" },
    { platform: "AOL Mail", category: "Email", portalUrl: "LE Page", portalLink: "https://www.verizonmedia.com/policies/law-enforcement", contact: "—" },
    { platform: "PhonePe", category: "E-Wallet", portalUrl: "Cyber Cell", portalLink: "https://cybercell.phonepe.com/", contact: "nodalofficer@phonepe.com" },
    { platform: "Paytm", category: "E-Wallet", portalUrl: "Contact", portalLink: "https://paytm.com/contact-us", contact: "nodal@paytm.com" },
    { platform: "Mobikwik", category: "E-Wallet", portalUrl: "Privacy", portalLink: "https://www.mobikwik.com/privacypolicy", contact: "—" },
    { platform: "SBI Buddy", category: "E-Wallet", portalUrl: "—", contact: "agm.nodcyb@sbi.co.in" },
    { platform: "BillDesk", category: "E-Wallet", portalUrl: "Security", portalLink: "https://www.billdesk.com/web/guest/security", contact: "—" },
    { platform: "FreeCharge", category: "E-Wallet", portalUrl: "Contact", portalLink: "https://www.freecharge.in/contact", contact: "—" },
    { platform: "Flipkart", category: "E-Commerce", portalUrl: "Help Centre", portalLink: "https://www.flipkart.com/helpcentre", contact: "grievance.officer@flipkart.com" },
    { platform: "Amazon", category: "E-Commerce", portalUrl: "Amazon Help", portalLink: "https://www.amazon.in/gp/help/customer/display.html", contact: "police-inquiries@amazon.in" },
    { platform: "OLX", category: "E-Commerce", portalUrl: "Help", portalLink: "https://help.olx.in/hc/en-us", contact: "support@olx.in" },
    { platform: "Snapdeal", category: "E-Commerce", portalUrl: "Help", portalLink: "https://www.snapdeal.com/help", contact: "grievance@snapdeal.com" },
    { platform: "JioMart", category: "E-Commerce", portalUrl: "Contact", portalLink: "https://www.jiomart.com/contactus", contact: "care@jiomart.com" },
    { platform: "Meesho", category: "E-Commerce", portalUrl: "Help", portalLink: "https://www.meesho.com/help", contact: "grievance@meesho.com" },
    { platform: "Myntra", category: "E-Commerce", portalUrl: "Contact", portalLink: "https://www.myntra.com/contactus", contact: "grievance@myntra.com" },
    { platform: "Ajio", category: "E-Commerce", portalUrl: "Help", portalLink: "https://www.ajio.com/help", contact: "customercare@ajio.com" },
    { platform: "Tata CLiQ", category: "E-Commerce", portalUrl: "Contact", portalLink: "https://www.cliqcare.com/contact-us", contact: "grievance@tatacliq.com" },
    { platform: "Shopify", category: "E-Commerce", portalUrl: "LE Page", portalLink: "https://www.shopify.com/legal/law-enforcement", contact: "—" },
    { platform: "IndiaMART", category: "E-Commerce", portalUrl: "Contact", portalLink: "https://www.indiamart.com/contactus/", contact: "grievance@indiamart.com" },
    { platform: "BookMyShow", category: "E-Commerce", portalUrl: "Support", portalLink: "https://support.bookmyshow.com/support/home", contact: "support@bookmyshow.com" },
    { platform: "eBay", category: "E-Commerce", portalUrl: "LE Page", portalLink: "https://www.ebay.com/help/policies/law-enforcement", contact: "—" },
    { platform: "Zomato", category: "Food Delivery", portalUrl: "Contact", portalLink: "https://www.zomato.com/contact", contact: "grievance@zomato.com" },
    { platform: "Swiggy", category: "Food Delivery", portalUrl: "Support", portalLink: "https://www.swiggy.com/support", contact: "grievance@swiggy.in" },
    { platform: "Domino’s", category: "Food Delivery", portalUrl: "Contact", portalLink: "https://www.dominos.co.in/contact-us", contact: "—" },
    { platform: "Dunzo", category: "Food Delivery", portalUrl: "Contact", portalLink: "https://www.dunzo.com/contact", contact: "support@dunzo.com" },
    { platform: "McDonald’s", category: "Food Delivery", portalUrl: "Contact", portalLink: "https://www.mcdonaldsindia.com/contact-us", contact: "—" },
    { platform: "KFC", category: "Food Delivery", portalUrl: "Contact", portalLink: "https://online.kfc.co.in/contact-us", contact: "—" },
    { platform: "Pizza Hut", category: "Food Delivery", portalUrl: "Contact", portalLink: "https://www.pizzahut.co.in/contact-us", contact: "—" },
    { platform: "Subway", category: "Food Delivery", portalUrl: "Contact", portalLink: "https://www.subway.com/en-IN/ContactUs", contact: "—" },
    { platform: "Binance", category: "Cryptocurrency", portalUrl: "LE Portal", portalLink: "https://www.binance.com/en/law-enforcement", contact: "—" },
    { platform: "Coinbase", category: "Cryptocurrency", portalUrl: "LE Portal", portalLink: "https://www.coinbase.com/legal/law-enforcement", contact: "—" },
    { platform: "MoonPay", category: "Cryptocurrency", portalUrl: "Legal", portalLink: "https://www.moonpay.com/legal", contact: "—" },
    { platform: "OpenSea", category: "Cryptocurrency", portalUrl: "Privacy", portalLink: "https://opensea.io/privacy", contact: "—" },
    { platform: "FTX US", category: "Cryptocurrency", portalUrl: "Privacy", portalLink: "https://ftx.us/privacy-policy", contact: "—" },
    { platform: "Hostinger", category: "Web Hosting", portalUrl: "Abuse", portalLink: "https://www.hostinger.com/report-abuse", contact: "abuse@hostinger.com" },
    { platform: "DreamHost", category: "Web Hosting", portalUrl: "Abuse", portalLink: "https://www.dreamhost.com/abuse/", contact: "abuse@dreamhost.com" },
    { platform: "HostGator", category: "Web Hosting", portalUrl: "Abuse", portalLink: "https://www.hostgator.com/help/article/reporting-abuse", contact: "abuse@hostgator.com" },
    { platform: "SiteGround", category: "Web Hosting", portalUrl: "Abuse", portalLink: "https://www.siteground.com/report-abuse", contact: "abuse@siteground.com" },
    { platform: "A2 Hosting", category: "Web Hosting", portalUrl: "Abuse", portalLink: "https://www.a2hosting.com/about-abuse", contact: "abuse@a2hosting.com" },
    { platform: "Dhani", category: "Loan App", portalUrl: "Contact", portalLink: "https://www.dhani.com/contact-us", contact: "—" },
    { platform: "MoneyTap", category: "Loan App", portalUrl: "Contact", portalLink: "https://moneytap.com/contact-us/", contact: "—" },
    { platform: "PaySense", category: "Loan App", portalUrl: "Contact", portalLink: "https://www.paysense.in/contact", contact: "—" },
    { platform: "CASHe", category: "Loan App", portalUrl: "Contact", portalLink: "https://www.cashe.co.in/contact", contact: "—" },
    { platform: "mPokket", category: "Loan App", portalUrl: "Contact", portalLink: "https://www.mpokket.com/contact", contact: "—" },
    { platform: "Money View", category: "Loan App", portalUrl: "Contact", portalLink: "https://moneyview.in/contact-us", contact: "—" },
    { platform: "NordVPN", category: "VPN", portalUrl: "Privacy", portalLink: "https://nordvpn.com/privacy-policy/", contact: "—" },
    { platform: "ExpressVPN", category: "VPN", portalUrl: "Privacy", portalLink: "https://www.expressvpn.com/privacy-policy", contact: "—" },
    { platform: "Surfshark", category: "VPN", portalUrl: "Privacy", portalLink: "https://surfshark.com/privacy", contact: "—" },
    { platform: "ProtonVPN", category: "VPN", portalUrl: "Privacy", portalLink: "https://protonvpn.com/privacy-policy", contact: "—" },
    { platform: "CyberGhost", category: "VPN", portalUrl: "Privacy", portalLink: "https://www.cyberghostvpn.com/en_US/privacy-policy", contact: "—" },
    { platform: "MakeMyTrip", category: "Travel", portalUrl: "Support", portalLink: "https://support.makemytrip.com/", contact: "—" },
    { platform: "Cleartrip", category: "Travel", portalUrl: "Support", portalLink: "https://www.cleartrip.com/support", contact: "—" },
    { platform: "Goibibo", category: "Travel", portalUrl: "Support", portalLink: "https://www.goibibo.com/support/", contact: "—" },
    { platform: "Ola Cabs", category: "Travel", portalUrl: "Help", portalLink: "https://help.olacabs.com/", contact: "—" },
    { platform: "Uber", category: "Travel", portalUrl: "Legal", portalLink: "https://www.uber.com/legal/en/document/", contact: "—" },
    { platform: "OYO Rooms", category: "Travel", portalUrl: "Contact", portalLink: "https://www.oyorooms.com/contactus/", contact: "—" },
    { platform: "Booking.com", category: "Travel", portalUrl: "Contact", portalLink: "https://www.booking.com/content/contact-us.html", contact: "—" },
];
